name: Bootstrap Jekyll
markdown: kramdown
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:categories/:year/:month/:day/:title/
baseurl: /
github_repo: https://github.com/minhongrails/bootstrap-jekyll
production_url: www.minh.io
default_feature_image: /assets/img/headers/autochrome-v3.jpg